<?php

function tlh_acf_add_local_field_groups() {

	acf_add_local_field_group(array(
		'key' => 'group_5a2e9029bdbc0',
		'title' => 'Color Selection',
		'fields' => array(
			array(
				'key' => 'field_5a2e90415fc7d',
				'label' => 'Color',
				'name' => 'color',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'primary' => 'Primary',
					'secondary' => 'Secondary',
					'custom' => 'Custom',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a2e90815fc7e',
				'label' => 'Custom Color',
				'name' => 'color_custom',
				'type' => 'extended-color-picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5a2e90415fc7d',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'color_palette' => '',
				'hide_palette' => 0,
			),
			array(
				'key' => 'field_5a2e90a55fc7f',
				'label' => 'Text Color',
				'name' => 'text_dark',
				'type' => 'true_false',
				'instructions' => 'If the background color is a very light color, enable this to make the text dark to help readability',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'Dark',
				'ui_off_text' => 'Light',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => 'This group is included in the Launch LP builder fields',
		'modified' => 1528997558,
	));

	acf_add_local_field_group(array(
		'key' => 'group_593e8e300118a',
		'title' => 'Custom CSS & JS',
		'fields' => array(
			array(
				'key' => 'field_593e8e5a4d763',
				'label' => 'Custom CSS',
				'name' => 'custom_css',
				'type' => 'acf_code_field',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_593e8e704d764',
				'label' => 'Custom JS',
				'name' => 'custom_js',
				'type' => 'acf_code_field',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'launch-lp',
				),
			),
		),
		'menu_order' => 100,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1521220137,
	));

	acf_add_local_field_group(array(
		'key' => 'group_5930ccfeb5901',
		'title' => 'Launch LP Content',
		'fields' => array(
			array(
				'key' => 'field_593782c983e5f',
				'label' => 'Hero',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5930cd50ae2c4',
				'label' => 'Hero Image',
				'name' => 'lp_hero_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => 'jpg,jpeg,png,svg',
			),
			array(
				'key' => 'field_5a2ff03d9bdae',
				'label' => 'Image Overlay',
				'name' => 'lp_hero_overlay',
				'type' => 'true_false',
				'instructions' => 'If a light hero image is used, enable this to help the logo and phone number stand out',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'On',
				'ui_off_text' => 'Off',
			),
			array(
				'key' => 'field_5930e1eb8afff',
				'label' => 'Logo Version',
				'name' => 'lp_logo_version',
				'type' => 'true_false',
				'instructions' => 'If the dark version of the logo isn\'t showing up well on the hero image, enable the light version of the logo',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'Light',
				'ui_off_text' => 'Dark',
			),
			array(
				'key' => 'field_5930cd8aae2c6',
				'label' => 'Hero Text',
				'name' => 'lp_hero_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5930cd63ae2c5',
				'label' => 'Form Code',
				'name' => 'lp_form_code',
				'type' => 'textarea',
				'instructions' => 'Example: &lt;script src="https://requestforms.learninghouse.com/form/show/[school]/ppc-form-multi-new/[000]/[0000]/[school-url]:thank-you:request_id" type="text/javascript"&gt;&lt;/script&gt;',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),
			array(
				'key' => 'field_593ad4aa0b6c6',
				'label' => 'Form Background Color',
				'name' => 'lp_form_color',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array(
					0 => 'group_5a2e9029bdbc0',
				),
				'display' => 'group',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
			),
			array(
				'key' => 'field_593782de83e60',
				'label' => 'Main Content',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5930cdb8ae2c7',
				'label' => 'Main Content Title',
				'name' => 'lp_main_content_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '60',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a2eed46f6ca1',
				'label' => 'Sidebar Title',
				'name' => 'lp_main_sidebar_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5930cdd6ae2c8',
				'label' => 'Main Content',
				'name' => 'lp_main_content',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '60',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_5a2eed0cf6ca0',
				'label' => 'Sidebar',
				'name' => 'lp_main_sidebar',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '40',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_593782ef83e61',
				'label' => 'Values',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a3293ed438f9',
				'label' => 'Values Title',
				'name' => 'lp_values_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a32940db3172',
				'label' => 'Values',
				'name' => 'lp_values',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5a329419b3173',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5a32941eb3174',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '70',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => 'wpautop',
					),
				),
			),
			array(
				'key' => 'field_5a329451b3175',
				'label' => 'Background Color',
				'name' => 'lp_values_color',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array(
					0 => 'group_5a2e9029bdbc0',
				),
				'display' => 'group',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
			),
			array(
				'key' => 'field_5a32949b1ee41',
				'label' => 'About',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a3294dbec6e8',
				'label' => 'About Title',
				'name' => 'lp_about_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a3294e9ec6e9',
				'label' => 'About Paragraph',
				'name' => 'lp_about_paragraph',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5a3294fbec6ea',
				'label' => 'Background Color',
				'name' => 'lp_about_color',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array(
					0 => 'group_5a2e9029bdbc0',
				),
				'display' => 'group',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
			),
			array(
				'key' => 'field_5937830b83e63',
				'label' => 'Call to Action',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5930cdf5ae2c9',
				'label' => 'Call to Action Text',
				'name' => 'lp_cta_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5930ce05ae2ca',
				'label' => 'Button Text',
				'name' => 'lp_cta_button',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a2eef3389fd5',
				'label' => 'Button Color',
				'name' => 'lp_cta_button_color',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array(
					0 => 'group_5a2e9029bdbc0',
				),
				'display' => 'group',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 1,
			),
			array(
				'key' => 'field_5a3294a41ee42',
				'label' => 'Accreditation',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a32953a0c1f0',
				'label' => 'Accreditation Title',
				'name' => 'lp_accreditation_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a3295490c1f1',
				'label' => 'Accreditation Paragraph',
				'name' => 'lp_accreditation_paragraph',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5a3295660c1f2',
				'label' => 'Accreditation Logos',
				'name' => 'lp_accreditation_logos',
				'type' => 'gallery',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'min' => '',
				'max' => '',
				'insert' => 'append',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'launch-lp',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => 'Launch LP page builder',
		'modified' => 1529002206,
	));

	acf_add_local_field_group(array(
		'key' => 'group_5a2ac273ddd14',
		'title' => 'Site Settings',
		'fields' => array(
			array(
				'key' => 'field_5a2b0ae9f47c7',
				'label' => 'School Info',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a2b0da0452a1',
				'label' => 'School Name',
				'name' => 'school_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a2ac2a7d5e00',
				'label' => 'School Address',
				'name' => 'school_address_1',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '123 Main Street',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a7a14504ce62',
				'label' => 'School Address Line 2',
				'name' => 'school_address_2',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'Not Chicago, IL 45678',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a2b0dc0452a2',
				'label' => 'School Phone Number',
				'name' => 'school_phone',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '(555) 555-5555',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a2b0e3f452a3',
				'label' => 'School Email Address',
				'name' => 'school_email_address',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'email@address.com',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5a2b0f2944292',
				'label' => 'Google Tag Manager ID',
				'name' => 'gtm_id',
				'type' => 'text',
				'instructions' => 'Enter the unique ID at the end of the url: https://www.googletagmanager.com/ns.html?id=GTM-<strong style="background-color: yellow;">xxxxxx</strong>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 123456,
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5a2b0a3af47c3',
				'label' => 'Social Links',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a2b0a4ef47c4',
				'label' => 'Social Links',
				'name' => 'social_links',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5a2b0a60f47c5',
						'label' => 'Service',
						'name' => 'service',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'Facebook' => 'Facebook',
							'Twitter' => 'Twitter',
							'Google Plus' => 'Google Plus',
							'LinkedIn' => 'LinkedIn',
						),
						'default_value' => array(
						),
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'ajax' => 0,
						'return_format' => 'value',
						'placeholder' => '',
					),
					array(
						'key' => 'field_5a2b0abcf47c6',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '70',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'https://www.twitter.com',
					),
				),
			),
			array(
				'key' => 'field_5a2b0b864656d',
				'label' => 'Branding',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5a2b0ba64656e',
				'label' => 'School Logo',
				'name' => 'school_logo',
				'type' => 'image',
				'instructions' => 'This is the primary logo, typically the full color version.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5a2b0bf84656f',
				'label' => 'School Logo Alternative',
				'name' => 'school_logo_alternative',
				'type' => 'image',
				'instructions' => 'Typically a monochrome white logo, used to show up easily on more varied backgrounds.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5a7a0e240eb90',
				'label' => 'School Logo Compact',
				'name' => 'school_logo_compact',
				'type' => 'image',
				'instructions' => 'This is a compact or simplified version of the primary logo, for when space is a concern.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5a7a0e920eb91',
				'label' => 'School Logo Compact Alternative',
				'name' => 'school_logo_compact_alternative',
				'type' => 'image',
				'instructions' => 'Typically a monochrome white logo, used to show up easily on more varied backgrounds. This is a compact or simplified version for when space is a concern.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5a2b0c5646570',
				'label' => 'Primary Color',
				'name' => 'color_1',
				'type' => 'color_picker',
				'instructions' => 'Used primarily for quickly customizing Launch LPs and other content in the WordPress admin',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5a2b0c6a46571',
				'label' => 'Secondary Color',
				'name' => 'color_2',
				'type' => 'color_picker',
				'instructions' => 'Used primarily for quickly customizing Launch LPs and other content in the WordPress admin',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'field_5a32b52ad36e7',
				'label' => 'Headings Font',
				'name' => 'headings_font',
				'type' => 'select',
				'instructions' => 'This font choice only applies to the Launch LPs',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'\'Open Sans\', Arial, sans-serif' => 'Open Sans',
					'\'Open Sans Condensed\', Arial, sans-serif' => 'Open Sans Condensed',
					'\'Merriweather\', Times New Roman, serif' => 'Merriweather',
					'\'PT Serif\', Times New Roman, serif' => 'PT Serif',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5a32b55fd36e8',
				'label' => 'Body Font',
				'name' => 'body_font',
				'type' => 'select',
				'instructions' => 'This font choice only applies to the Launch LPs',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'\'Open Sans\', Arial, sans-serif' => 'Open Sans',
					'\'Open Sans Condensed\', Arial, sans-serif' => 'Open Sans Condensed',
					'\'Merriweather\', Times New Roman, serif' => 'Merriweather',
					'\'PT Serif\', Times New Roman, serif' => 'PT Serif',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5b3688110a7aa',
				'label' => 'Favicon',
				'name' => 'favicon',
				'type' => 'image',
				'instructions' => 'Please upload a 32x32 png',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => 32,
				'min_height' => 32,
				'min_size' => '',
				'max_width' => 32,
				'max_height' => 32,
				'max_size' => '',
				'mime_types' => 'png',
			),
			array(
				'key' => 'field_5b368a9d1a887',
				'label' => 'Thank You Page',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5b368ae41a88b',
				'label' => 'Background Image',
				'name' => 'thank_you_background_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-general-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1530302360,
	));

}
add_action('acf/init', 'tlh_acf_add_local_field_groups');

?>
